import type { Metadata } from "next";
import "./global.css";
import { Inter } from "next/font/google";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import NavBar from "@/app/components/helper/NavBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme accentColor="violet">
          {/* <NavBar /> */}
          <main className="">
            <Container>{children}</Container>
          </main>
        </Theme>
      </body>
    </html>
  );
}
